<?php

/**
   * @name:        Product table seeder
   * @author:      Zaid - Patrik - Henry
   * @description: insert datos in the database
   * @version:     1.0
   * @date         26/05/2020
   * @param        none
   * @return       none
   */

use Illuminate\Database\Seeder;

class ProductTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * @return void
     */
    public function run()
    {
        DB::table('products')->insert(['id' =>1,'clubid' =>1,'productname' =>'Martini','description' =>'Most drinkers, excluding beer and whiskey, often order martini when looking for a simple, familiar drink.','image' =>'null','price' =>15,'status' =>1,'category' =>'Cocktail',]);
        DB::table('products')->insert(['id' =>2,'clubid' =>1,'productname' =>'Manhattan','description' =>'It is fun and sweet, although you must take care of the alcoholic state of the girls who sit at your bar, otherwise you will end up being a caretaker.','image' =>'null','price' =>20,'status' =>1,'category' =>'Cocktail',]);
        DB::table('products')->insert(['id' =>3,'clubid' =>1,'productname' =>'The Old Fashioned','description' =>'This classic drink is one of the basic ones associated with movie scenes where gangsters play life in poker and prop their glass with a drink on the felt. Perhaps, this is another stigmatization. A drink of men and friends.','image' =>'null','price' =>20,'status' =>1,'category' =>'Cocktail',]);
        DB::table('products')->insert(['id' =>4,'clubid' =>1,'productname' =>'The Sidecar','description' =>'It is intended for a rather casual audience, seeking to test your talents as a bartender. It is a somewhat more sour drink that is produced with a base of Brandy and Cointreau.','image' =>'null','price' =>20,'status' =>1,'category' =>'Cocktail',]);
        DB::table('products')->insert(['id' =>5,'clubid' =>1,'productname' =>'Daiquiri','description' =>'It is ideal for drinking on the beach as it is closely associated with vacation spots. With different fruits you will make all tastes.','image' =>'null','price' =>25,'status' =>1,'category' =>'Cocktail',]);
        DB::table('products')->insert(['id' =>6,'clubid' =>2,'productname' =>'Mojito','description' =>'This drink is a very popular drink of Cuban origin. To prepare, gently squeeze lemon juice, sugar and mint leaves with a "mess." Add white rum with a little soda water, and fill the glass with ice. There are many variations, such as apple and berry mojitos, that use flavored liqueurs.','image' =>'null','price' =>25,'status' =>1,'category' =>'Cocktail',]);
        DB::table('products')->insert(['id' =>7,'clubid' =>2,'productname' =>'Cosmopolitan','description' =>'The «cosmopolitan» are a vodka cocktail based on Triple Sec (an orange-flavored liqueur), cranberry juice and lemon juice. They are served in martini glasses, sometimes with a lemon wedge for garnish.','image' =>'null','price' =>20,'status' =>1,'category' =>'Cocktail',]);
        DB::table('products')->insert(['id' =>8,'clubid' =>2,'productname' =>'Margarita','description' =>'There are many variations, but a classic margarita has tequila, Triple Sec, and lime or lemon juice.','image' =>'null','price' =>25,'status' =>1,'category' =>'Cocktail',]);
        DB::table('products')->insert(['id' =>9,'clubid' =>2,'productname' =>'Mai Tai','description' =>'It is a sweet cocktail in combination of white rum, dark rum, curaçao orange, pineapple juice, sugar syrup and lemon juice.','image' =>'null','price' =>20,'status' =>1,'category' =>'Cocktail',]);
        DB::table('products')->insert(['id' =>10,'clubid' =>2,'productname' =>'Caipirinha','description' =>'The main ingredient of this famous Brazilian drink is cachaça, a spirit similar to rum that is made from fermented sugar cane. It is a simple cocktail: a lime is cut into pieces and added in a glass with the sugar. The crushed ice is added to the glass and then the cachaça is poured.','image' =>'null','price' =>25,'status' =>1,'category' =>'Cocktail',]);
        DB::table('products')->insert(['id' =>11,'clubid' =>2,'productname' =>'Daiquiri','description' =>'Strawberry, banana, and melon daiquiris are very popular, as are frozen daiquiris where the glass is filled with crushed ice. The original recipe is simply white rum, sugar syrup, and lemon juice combined in a cocktail shaker and poured into a chilled martini glass.','image' =>'null','price' =>25,'status' =>1,'category' =>'Cocktail',]);
        DB::table('products')->insert(['id' =>12,'clubid' =>2,'productname' =>'Piña Colada','description' =>'Pina colada is the national drink of Puerto Rico. Contains white rum, coconut, cream and pineapple juice. It is served in a large glass with crushed ice.','image' =>'null','price' =>20,'status' =>1,'category' =>'Cocktail',]);
        DB::table('products')->insert(['id' =>13,'clubid' =>4,'productname' =>'Long Island Ice Tea','description' =>'Vodka, tequila, gin, rum, triple sec, and a little coke are poured into a cocktail shaker and mixed thoroughly before pouring into a tall glass. Sometimes sugar syrup or "sweet and sour mix" (a mixture of lemon juice and sugar) is also added.','image' =>'null','price' =>25,'status' =>1,'category' =>'Cocktail',]);
        DB::table('products')->insert(['id' =>14,'clubid' =>4,'productname' =>'White Russian','description' =>'Vodka, coffee liquor such as Tia Maria, and Bailey mix together. Ice can be added. This drink is so named because its main ingredient is vodka, although it is believed to have originated in the USA.','image' =>'null','price' =>20,'status' =>1,'category' =>'Cocktail',]);
        DB::table('products')->insert(['id' =>15,'clubid' =>4,'productname' =>'Blue Hawaii','description' =>'Although the combination of ingredients has evolved, Blue Hawaii maintains rum as a base drink and the classic umbrella as garnish.','image' =>'null','price' =>25,'status' =>1,'category' =>'Cocktail',]);
        DB::table('products')->insert(['id' =>16,'clubid' =>5,'productname' =>'Coco Loco','description' =>'A refreshing summer cocktail with a lot of flavor to the fruit of the palm tree.','image' =>'null','price' =>30,'status' =>1,'category' =>'Cocktail',]);
        DB::table('products')->insert(['id' =>17,'clubid' =>5,'productname' =>'Oceans','description' =>'Its first steps are taken in the 1930s. The cocktail was invented by Ernest Raymond Beaumont-Gannt at Hollywoods Don Beachcomber Restaurant. The Zombie became popular soon after, in the following decade.','image' =>'null','price' =>25,'status' =>1,'category' =>'Cocktail',]);
        DB::table('products')->insert(['id' =>18,'clubid' =>5,'productname' =>'Tom Collins','description' =>'Tom Collins appeared in Thomass The Bartenders Guide in 1876, and soon after was a popular cocktail in the USA.','image' =>'null','price' =>20,'status' =>1,'category' =>'Cocktail',]);
        DB::table('products')->insert(['id' =>19,'clubid' =>5,'productname' =>'Negroni','description' =>'When Christmas arrives, the smallest of the house think of the gifts and the oldest of the food they should prepare for their guests. An original and simple way to start those evenings is with an aperitif cocktail. Like the Negroni.','image' =>'null','price' =>20,'status' =>1,'category' =>'Cocktail',]);
        DB::table('products')->insert(['id' =>20,'clubid' =>3,'productname' =>'Hurricane','description' =>'The origin of this drink is attributed to Mr. Pat OBrien, owner of a bar in his name in the largest city in the state of Louisiana','image' =>'null','price' =>25,'status' =>1,'category' =>'Cocktail',]);
        DB::table('products')->insert(['id' =>21,'clubid' =>3,'productname' =>'Gin&Tonic','description' =>'This classic cocktail was created by British soldiers, during their occupation of India, who combined with a little breast milk (colloquially called London Dry Gin) their daily ration of quinine (to fight malaria) and lime ( to prevent scurvy).','image' =>'null','price' =>20,'status' =>1,'category' =>'Cocktail',]);
        DB::table('products')->insert(['id' =>22,'clubid' =>3,'productname' =>'Sea Breeze','description' =>'The Sea Breeze was born at the time of the American prohibition, back in the 20s and 30s, with a totally different recipe from the one it currently has, since it was made from gin and grenadine.','image' =>'null','price' =>20,'status' =>1,'category' =>'Cocktail',]);
        DB::table('products')->insert(['id' =>23,'clubid' =>3,'productname' =>'Farnell','description' =>'Phrases that start with there is nothing better are usually topical and repetitive, but not false. And, friends, there is nothing better than having a fresh cocktail on a terrace next to the beach. Or in the pool','image' =>'null','price' =>20,'status' =>1,'category' =>'Cocktail',]);
        DB::table('products')->insert(['id' =>24,'clubid' =>3,'productname' =>'Godfather','description' =>'Although for them you must have a solid palate, because the combination of flavors is packaging.','image' =>'null','price' =>20,'status' =>1,'category' =>'Cocktail',]);
        DB::table('products')->insert(['id' =>25,'clubid' =>1,'productname' =>'Ticket','description' =>'Normal Ticket','image' =>'null','price' =>10,'status' =>1,'category' =>'Ticket',]);
        DB::table('products')->insert(['id' =>26,'clubid' =>2,'productname' =>'Ticket','description' =>'Normal Ticket','image' =>'null','price' =>15,'status' =>1,'category' =>'Ticket',]);
        DB::table('products')->insert(['id' =>27,'clubid' =>4,'productname' =>'Ticket','description' =>'Normal Ticket','image' =>'null','price' =>10,'status' =>1,'category' =>'Ticket',]);
        DB::table('products')->insert(['id' =>28,'clubid' =>5,'productname' =>'Ticket','description' =>'Normal Ticket','image' =>'null','price' =>10,'status' =>1,'category' =>'Ticket',]);
        DB::table('products')->insert(['id' =>29,'clubid' =>3,'productname' =>'Ticket','description' =>'Normal Ticket','image' =>'null','price' =>15,'status' =>1,'category' =>'Ticket',]);
        DB::table('products')->insert(['id' =>30,'clubid' =>1,'productname' =>'Ticket','description' =>'Christmas Ticket','image' =>'null','price' =>20,'status' =>1,'category' =>'Ticket',]);
        DB::table('products')->insert(['id' =>31,'clubid' =>2,'productname' =>'Ticket','description' =>'Christmas Ticket','image' =>'null','price' =>20,'status' =>1,'category' =>'Ticket',]);
        DB::table('products')->insert(['id' =>32,'clubid' =>4,'productname' =>'Ticket','description' =>'Christmas Ticket','image' =>'null','price' =>20,'status' =>1,'category' =>'Ticket',]);
        DB::table('products')->insert(['id' =>33,'clubid' =>5,'productname' =>'Ticket','description' =>'Christmas Ticket','image' =>'null','price' =>20,'status' =>1,'category' =>'Ticket',]);
        DB::table('products')->insert(['id' =>34,'clubid' =>5,'productname' =>'Ticket','description' =>'Christmas Ticket','image' =>'null','price' =>20,'status' =>1,'category' =>'Ticket',]);
        DB::table('products')->insert(['id' =>35,'clubid' =>1,'productname' =>'Red Bull','description' =>'Energy drink','image' =>'null','price' =>5,'status' =>1,'category' =>'Refreshing drink',]);
        DB::table('products')->insert(['id' =>36,'clubid' =>2,'productname' =>'Red Bull','description' =>'Energy drink','image' =>'null','price' =>5,'status' =>1,'category' =>'Refreshing drink',]);
        DB::table('products')->insert(['id' =>37,'clubid' =>3,'productname' =>'Red Bull','description' =>'Energy drink','image' =>'null','price' =>5,'status' =>1,'category' =>'Refreshing drink',]);
        DB::table('products')->insert(['id' =>38,'clubid' =>4,'productname' =>'Red Bull','description' =>'Energy drink','image' =>'null','price' =>5,'status' =>1,'category' =>'Refreshing drink',]);
        DB::table('products')->insert(['id' =>39,'clubid' =>5,'productname' =>'Red Bull','description' =>'Energy drink','image' =>'null','price' =>5,'status' =>1,'category' =>'Refreshing drink',]);
        DB::table('products')->insert(['id' =>40,'clubid' =>1,'productname' =>'Coca Cola','description' =>'Soda and refreshing drink','image' =>'null','price' =>5,'status' =>1,'category' =>'Refreshing drink',]);
        DB::table('products')->insert(['id' =>41,'clubid' =>2,'productname' =>'Coca Cola','description' =>'Soda and refreshing drink','image' =>'null','price' =>5,'status' =>1,'category' =>'Refreshing drink',]);
        DB::table('products')->insert(['id' =>42,'clubid' =>3,'productname' =>'Coca Cola','description' =>'Soda and refreshing drink','image' =>'null','price' =>5,'status' =>1,'category' =>'Refreshing drink',]);
        DB::table('products')->insert(['id' =>43,'clubid' =>4,'productname' =>'Coca Cola','description' =>'Soda and refreshing drink','image' =>'null','price' =>5,'status' =>1,'category' =>'Refreshing drink',]);
        DB::table('products')->insert(['id' =>44,'clubid' =>5,'productname' =>'Coca Cola','description' =>'Soda and refreshing drink','image' =>'null','price' =>5,'status' =>1,'category' =>'Refreshing drink',]);
        DB::table('products')->insert(['id' =>45,'clubid' =>1,'productname' =>'Water','description' =>'Water','image' =>'null','price' =>3,'status' =>1,'category' =>'Refreshing drink',]);
        DB::table('products')->insert(['id' =>46,'clubid' =>2,'productname' =>'Water','description' =>'Water','image' =>'null','price' =>3,'status' =>1,'category' =>'Refreshing drink',]);
        DB::table('products')->insert(['id' =>47,'clubid' =>3,'productname' =>'Water','description' =>'Water','image' =>'null','price' =>3,'status' =>1,'category' =>'Refreshing drink',]);
        DB::table('products')->insert(['id' =>48,'clubid' =>4,'productname' =>'Water','description' =>'Water','image' =>'null','price' =>3,'status' =>1,'category' =>'Refreshing drink',]);
        DB::table('products')->insert(['id' =>49,'clubid' =>5,'productname' =>'Water','description' =>'Water','image' =>'null','price' =>3,'status' =>1,'category' =>'Refreshing drink',]);
        DB::table('products')->insert(['id' =>50,'clubid' =>1,'productname' =>'JOHNNIE WALKER RED LABEL','description' =>'Johnnie Walker is a brand of Scotch whiskey','image' =>'null','price' =>50,'status' =>1,'category' =>'Liqueur',]);
        DB::table('products')->insert(['id' =>51,'clubid' =>1,'productname' =>'JOHNNIE WALKER BLUE LABEL','description' =>'Johnnie Walker is a brand of Scotch whiskey','image' =>'null','price' =>80,'status' =>1,'category' =>'Liqueur',]);
        DB::table('products')->insert(['id' =>52,'clubid' =>1,'productname' =>'JOHNNIE WALKER BLACK LABEL','description' =>'Johnnie Walker is a brand of Scotch whiskey','image' =>'null','price' =>70,'status' =>1,'category' =>'Liqueur',]);
        DB::table('products')->insert(['id' =>53,'clubid' =>1,'productname' =>'JOHNNIE WALKER GREEN LABEL','description' =>'Johnnie Walker is a brand of Scotch whiskey','image' =>'null','price' =>90,'status' =>1,'category' =>'Liqueur',]);
        DB::table('products')->insert(['id' =>54,'clubid' =>1,'productname' =>'JOHNNIE WALKER GOLD LABEL','description' =>'Johnnie Walker is a brand of Scotch whiskey','image' =>'null','price' =>120,'status' =>1,'category' =>'Liqueur',]);
        DB::table('products')->insert(['id' =>55,'clubid' =>1,'productname' =>'JOHNNIE WALKER SILVER LABEL','description' =>'Johnnie Walker is a brand of Scotch whiskey','image' =>'null','price' =>100,'status' =>1,'category' =>'Liqueur',]);
        DB::table('products')->insert(['id' =>56,'clubid' =>2,'productname' =>'JOHNNIE WALKER RED LABEL','description' =>'Johnnie Walker is a brand of Scotch whiskey','image' =>'null','price' =>50,'status' =>1,'category' =>'Liqueur',]);
        DB::table('products')->insert(['id' =>57,'clubid' =>2,'productname' =>'JOHNNIE WALKER BLUE LABEL','description' =>'Johnnie Walker is a brand of Scotch whiskey','image' =>'null','price' =>80,'status' =>1,'category' =>'Liqueur',]);
        DB::table('products')->insert(['id' =>58,'clubid' =>2,'productname' =>'JOHNNIE WALKER BLACK LABEL','description' =>'Johnnie Walker is a brand of Scotch whiskey','image' =>'null','price' =>70,'status' =>1,'category' =>'Liqueur',]);
        DB::table('products')->insert(['id' =>59,'clubid' =>2,'productname' =>'JOHNNIE WALKER GREEN LABEL','description' =>'Johnnie Walker is a brand of Scotch whiskey','image' =>'null','price' =>90,'status' =>1,'category' =>'Liqueur',]);
        DB::table('products')->insert(['id' =>60,'clubid' =>2,'productname' =>'JOHNNIE WALKER GOLD LABEL','description' =>'Johnnie Walker is a brand of Scotch whiskey','image' =>'null','price' =>120,'status' =>1,'category' =>'Liqueur',]);
        DB::table('products')->insert(['id' =>61,'clubid' =>2,'productname' =>'JOHNNIE WALKER SILVER LABEL','description' =>'Johnnie Walker is a brand of Scotch whiskey','image' =>'null','price' =>100,'status' =>1,'category' =>'Liqueur',]);
        DB::table('products')->insert(['id' =>62,'clubid' =>3,'productname' =>'JOHNNIE WALKER RED LABEL','description' =>'Johnnie Walker is a brand of Scotch whiskey','image' =>'null','price' =>50,'status' =>1,'category' =>'Liqueur',]);
        DB::table('products')->insert(['id' =>63,'clubid' =>3,'productname' =>'JOHNNIE WALKER BLUE LABEL','description' =>'Johnnie Walker is a brand of Scotch whiskey','image' =>'null','price' =>80,'status' =>1,'category' =>'Liqueur',]);
        DB::table('products')->insert(['id' =>64,'clubid' =>3,'productname' =>'JOHNNIE WALKER BLACK LABEL','description' =>'Johnnie Walker is a brand of Scotch whiskey','image' =>'null','price' =>70,'status' =>1,'category' =>'Liqueur',]);
        DB::table('products')->insert(['id' =>65,'clubid' =>3,'productname' =>'JOHNNIE WALKER GREEN LABEL','description' =>'Johnnie Walker is a brand of Scotch whiskey','image' =>'null','price' =>90,'status' =>1,'category' =>'Liqueur',]);
        DB::table('products')->insert(['id' =>66,'clubid' =>3,'productname' =>'JOHNNIE WALKER GOLD LABEL','description' =>'Johnnie Walker is a brand of Scotch whiskey','image' =>'null','price' =>120,'status' =>1,'category' =>'Liqueur',]);
        DB::table('products')->insert(['id' =>67,'clubid' =>3,'productname' =>'JOHNNIE WALKER SILVER LABEL','description' =>'Johnnie Walker is a brand of Scotch whiskey','image' =>'null','price' =>100,'status' =>1,'category' =>'Liqueur',]);
        DB::table('products')->insert(['id' =>68,'clubid' =>4,'productname' =>'JOHNNIE WALKER RED LABEL','description' =>'Johnnie Walker is a brand of Scotch whiskey','image' =>'null','price' =>50,'status' =>1,'category' =>'Liqueur',]);
        DB::table('products')->insert(['id' =>69,'clubid' =>4,'productname' =>'JOHNNIE WALKER BLUE LABEL','description' =>'Johnnie Walker is a brand of Scotch whiskey','image' =>'null','price' =>80,'status' =>1,'category' =>'Liqueur',]);
        DB::table('products')->insert(['id' =>70,'clubid' =>4,'productname' =>'JOHNNIE WALKER BLACK LABEL','description' =>'Johnnie Walker is a brand of Scotch whiskey','image' =>'null','price' =>70,'status' =>1,'category' =>'Liqueur',]);
        DB::table('products')->insert(['id' =>71,'clubid' =>4,'productname' =>'JOHNNIE WALKER GREEN LABEL','description' =>'Johnnie Walker is a brand of Scotch whiskey','image' =>'null','price' =>90,'status' =>1,'category' =>'Liqueur',]);
        DB::table('products')->insert(['id' =>72,'clubid' =>4,'productname' =>'JOHNNIE WALKER GOLD LABEL','description' =>'Johnnie Walker is a brand of Scotch whiskey','image' =>'null','price' =>120,'status' =>1,'category' =>'Liqueur',]);
        DB::table('products')->insert(['id' =>73,'clubid' =>4,'productname' =>'JOHNNIE WALKER SILVER LABEL','description' =>'Johnnie Walker is a brand of Scotch whiskey','image' =>'null','price' =>100,'status' =>1,'category' =>'Liqueur',]);
        DB::table('products')->insert(['id' =>74,'clubid' =>5,'productname' =>'JOHNNIE WALKER RED LABEL','description' =>'Johnnie Walker is a brand of Scotch whiskey','image' =>'null','price' =>50,'status' =>1,'category' =>'Liqueur',]);
        DB::table('products')->insert(['id' =>75,'clubid' =>5,'productname' =>'JOHNNIE WALKER BLUE LABEL','description' =>'Johnnie Walker is a brand of Scotch whiskey','image' =>'null','price' =>80,'status' =>1,'category' =>'Liqueur',]);
        DB::table('products')->insert(['id' =>76,'clubid' =>5,'productname' =>'JOHNNIE WALKER BLACK LABEL','description' =>'Johnnie Walker is a brand of Scotch whiskey','image' =>'null','price' =>70,'status' =>1,'category' =>'Liqueur',]);
        DB::table('products')->insert(['id' =>77,'clubid' =>5,'productname' =>'JOHNNIE WALKER GREEN LABEL','description' =>'Johnnie Walker is a brand of Scotch whiskey','image' =>'null','price' =>90,'status' =>1,'category' =>'Liqueur',]);
        DB::table('products')->insert(['id' =>78,'clubid' =>5,'productname' =>'JOHNNIE WALKER GOLD LABEL','description' =>'Johnnie Walker is a brand of Scotch whiskey','image' =>'null','price' =>120,'status' =>1,'category' =>'Liqueur',]);
        DB::table('products')->insert(['id' =>79,'clubid' =>5,'productname' =>'JOHNNIE WALKER SILVER LABEL','description' =>'Johnnie Walker is a brand of Scotch whiskey','image' =>'null','price' =>100,'status' =>1,'category' =>'Liqueur',]);
        DB::table('products')->insert(['id' =>80,'clubid' =>1,'productname' =>'Red Label Service','description' =>'Johnnie Walker with refreshing drink to choose','image' =>'null','price' =>100,'status' =>1,'category' =>'Service',]);
        DB::table('products')->insert(['id' =>81,'clubid' =>1,'productname' =>'Blue Label Service','description' =>'Johnnie Walker with refreshing drink to choose','image' =>'null','price' =>130,'status' =>1,'category' =>'Service',]);
        DB::table('products')->insert(['id' =>82,'clubid' =>1,'productname' =>'Black Label Service','description' =>'Johnnie Walker with refreshing drink to choose','image' =>'null','price' =>120,'status' =>1,'category' =>'Service',]);
        DB::table('products')->insert(['id' =>83,'clubid' =>1,'productname' =>'Green Label Service','description' =>'Johnnie Walker with refreshing drink to choose','image' =>'null','price' =>140,'status' =>1,'category' =>'Service',]);
        DB::table('products')->insert(['id' =>84,'clubid' =>1,'productname' =>'Gold Label Service','description' =>'Johnnie Walker with refreshing drink to choose','image' =>'null','price' =>220,'status' =>1,'category' =>'Service',]);
        DB::table('products')->insert(['id' =>85,'clubid' =>1,'productname' =>'Silver Label Service','description' =>'Johnnie Walker with refreshing drink to choose','image' =>'null','price' =>200,'status' =>1,'category' =>'Service',]);
        DB::table('products')->insert(['id' =>86,'clubid' =>2,'productname' =>'Red Label Service','description' =>'Johnnie Walker with refreshing drink to choose','image' =>'null','price' =>100,'status' =>1,'category' =>'Service',]);
        DB::table('products')->insert(['id' =>87,'clubid' =>2,'productname' =>'Blue Label Service','description' =>'Johnnie Walker with refreshing drink to choose','image' =>'null','price' =>130,'status' =>1,'category' =>'Service',]);
        DB::table('products')->insert(['id' =>88,'clubid' =>2,'productname' =>'Black Label Service','description' =>'Johnnie Walker with refreshing drink to choose','image' =>'null','price' =>120,'status' =>1,'category' =>'Service',]);
        DB::table('products')->insert(['id' =>89,'clubid' =>2,'productname' =>'Green Label Service','description' =>'Johnnie Walker with refreshing drink to choose','image' =>'null','price' =>140,'status' =>1,'category' =>'Service',]);
        DB::table('products')->insert(['id' =>90,'clubid' =>2,'productname' =>'Gold Label Service','description' =>'Johnnie Walker with refreshing drink to choose','image' =>'null','price' =>220,'status' =>1,'category' =>'Service',]);
        DB::table('products')->insert(['id' =>91,'clubid' =>2,'productname' =>'Silver Label Service','description' =>'Johnnie Walker with refreshing drink to choose','image' =>'null','price' =>200,'status' =>1,'category' =>'Service',]);
        DB::table('products')->insert(['id' =>92,'clubid' =>3,'productname' =>'Red Label Service','description' =>'Johnnie Walker with refreshing drink to choose','image' =>'null','price' =>100,'status' =>1,'category' =>'Service',]);
        DB::table('products')->insert(['id' =>93,'clubid' =>3,'productname' =>'Blue Label Service','description' =>'Johnnie Walker with refreshing drink to choose','image' =>'null','price' =>130,'status' =>1,'category' =>'Service',]);
        DB::table('products')->insert(['id' =>94,'clubid' =>3,'productname' =>'Black Label Service','description' =>'Johnnie Walker with refreshing drink to choose','image' =>'null','price' =>120,'status' =>1,'category' =>'Service',]);
        DB::table('products')->insert(['id' =>95,'clubid' =>3,'productname' =>'Green Label Service','description' =>'Johnnie Walker with refreshing drink to choose','image' =>'null','price' =>140,'status' =>1,'category' =>'Service',]);
        DB::table('products')->insert(['id' =>96,'clubid' =>3,'productname' =>'Gold Label Service','description' =>'Johnnie Walker with refreshing drink to choose','image' =>'null','price' =>220,'status' =>1,'category' =>'Service',]);
        DB::table('products')->insert(['id' =>97,'clubid' =>3,'productname' =>'Silver Label Service','description' =>'Johnnie Walker with refreshing drink to choose','image' =>'null','price' =>200,'status' =>1,'category' =>'Service',]);
        DB::table('products')->insert(['id' =>98,'clubid' =>4,'productname' =>'Red Label Service','description' =>'Johnnie Walker with refreshing drink to choose','image' =>'null','price' =>100,'status' =>1,'category' =>'Service',]);
        DB::table('products')->insert(['id' =>99,'clubid' =>4,'productname' =>'Blue Label Service','description' =>'Johnnie Walker with refreshing drink to choose','image' =>'null','price' =>130,'status' =>1,'category' =>'Service',]);
        DB::table('products')->insert(['id' =>100,'clubid' =>4,'productname' =>'Black Label Service','description' =>'Johnnie Walker with refreshing drink to choose','image' =>'null','price' =>120,'status' =>1,'category' =>'Service',]);
        DB::table('products')->insert(['id' =>101,'clubid' =>4,'productname' =>'Green Label Service','description' =>'Johnnie Walker with refreshing drink to choose','image' =>'null','price' =>140,'status' =>1,'category' =>'Service',]);
        DB::table('products')->insert(['id' =>102,'clubid' =>4,'productname' =>'Gold Label Service','description' =>'Johnnie Walker with refreshing drink to choose','image' =>'null','price' =>220,'status' =>1,'category' =>'Service',]);
        DB::table('products')->insert(['id' =>103,'clubid' =>4,'productname' =>'Silver Label Service','description' =>'Johnnie Walker with refreshing drink to choose','image' =>'null','price' =>200,'status' =>1,'category' =>'Service',]);
        DB::table('products')->insert(['id' =>104,'clubid' =>5,'productname' =>'Red Label Service','description' =>'Johnnie Walker with refreshing drink to choose','image' =>'null','price' =>100,'status' =>1,'category' =>'Service',]);
        DB::table('products')->insert(['id' =>105,'clubid' =>5,'productname' =>'Blue Label Service','description' =>'Johnnie Walker with refreshing drink to choose','image' =>'null','price' =>130,'status' =>1,'category' =>'Service',]);
        DB::table('products')->insert(['id' =>106,'clubid' =>5,'productname' =>'Black Label Service','description' =>'Johnnie Walker with refreshing drink to choose','image' =>'null','price' =>120,'status' =>1,'category' =>'Service',]);
        DB::table('products')->insert(['id' =>107,'clubid' =>5,'productname' =>'Green Label Service','description' =>'Johnnie Walker with refreshing drink to choose','image' =>'null','price' =>140,'status' =>1,'category' =>'Service',]);
        DB::table('products')->insert(['id' =>108,'clubid' =>5,'productname' =>'Gold Label Service','description' =>'Johnnie Walker with refreshing drink to choose','image' =>'null','price' =>220,'status' =>1,'category' =>'Service',]);
        DB::table('products')->insert(['id' =>109,'clubid' =>5,'productname' =>'Silver Label Service','description' =>'Johnnie Walker with refreshing drink to choose','image' =>'null','price' =>200,'status' =>1,'category' =>'Service',]);

        DB::table('products')->insert(['id' =>200,'clubid' =>6,'productname' =>'Martini','description' =>'Most drinkers, excluding beer and whiskey, often order martini when looking for a simple, familiar drink.','image' =>'null','price' =>15,'status' =>1,'category' =>'Cocktail',]);
        DB::table('products')->insert(['id' =>201,'clubid' =>6,'productname' =>'Manhattan','description' =>'It is fun and sweet, although you must take care of the alcoholic state of the girls who sit at your bar, otherwise you will end up being a caretaker.','image' =>'null','price' =>20,'status' =>1,'category' =>'Cocktail',]);
        DB::table('products')->insert(['id' =>202,'clubid' =>6,'productname' =>'The Old Fashioned','description' =>'This classic drink is one of the basic ones associated with movie scenes where gangsters play life in poker and prop their glass with a drink on the felt. Perhaps, this is another stigmatization. A drink of men and friends.','image' =>'null','price' =>20,'status' =>1,'category' =>'Cocktail',]);
        DB::table('products')->insert(['id' =>203,'clubid' =>6,'productname' =>'The Sidecar','description' =>'It is intended for a rather casual audience, seeking to test your talents as a bartender. It is a somewhat more sour drink that is produced with a base of Brandy and Cointreau.','image' =>'null','price' =>20,'status' =>1,'category' =>'Cocktail',]);
        DB::table('products')->insert(['id' =>204,'clubid' =>6,'productname' =>'Red Label Service','description' =>'Johnnie Walker with refreshing drink to choose','image' =>'null','price' =>100,'status' =>1,'category' =>'Service',]);
        DB::table('products')->insert(['id' =>205,'clubid' =>6,'productname' =>'Blue Label Service','description' =>'Johnnie Walker with refreshing drink to choose','image' =>'null','price' =>130,'status' =>1,'category' =>'Service',]);
        DB::table('products')->insert(['id' =>206,'clubid' =>6,'productname' =>'Black Label Service','description' =>'Johnnie Walker with refreshing drink to choose','image' =>'null','price' =>120,'status' =>1,'category' =>'Service',]);
        DB::table('products')->insert(['id' =>207,'clubid' =>6,'productname' =>'Green Label Service','description' =>'Johnnie Walker with refreshing drink to choose','image' =>'null','price' =>140,'status' =>1,'category' =>'Service',]);
        DB::table('products')->insert(['id' =>208,'clubid' =>6,'productname' =>'Gold Label Service','description' =>'Johnnie Walker with refreshing drink to choose','image' =>'null','price' =>220,'status' =>1,'category' =>'Service',]);
        DB::table('products')->insert(['id' =>209,'clubid' =>6,'productname' =>'Silver Label Service','description' =>'Johnnie Walker with refreshing drink to choose','image' =>'null','price' =>200,'status' =>1,'category' =>'Service',]);
        DB::table('products')->insert(['id' =>210,'clubid' =>6,'productname' =>'Water','description' =>'Water','image' =>'null','price' =>3,'status' =>1,'category' =>'Refreshing drink',]);
        DB::table('products')->insert(['id' =>211,'clubid' =>6,'productname' =>'Ticket','description' =>'Christmas Ticket','image' =>'null','price' =>20,'status' =>1,'category' =>'Ticket',]);


    }
}
